title: Phala Cloud Docs
description: Phala Cloud is a cloud service that allows you to deploy arbitrary dockerized applications into TEE.
baseurl: "/phala-cloud-community"
url: "https://phala-network.github.io"
markdown: kramdown
highlighter: rouge
permalink: pretty
include:
  - imgs

# Enable search
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

remote_theme: just-the-docs/just-the-docs@v0.7.0
# theme: just-the-docs  # Comment out for GitHub Pages
just_the_docs:
  nav_fold: false
  nav_level: 2
  collapse_inactive_sections: false
  expand_all: true
  collections:
    docs:
      output: true
  nav_order: 1

# Force all pages to use default layout
defaults:
  - scope:
      path: "" # All files
    values:
      layout: default
      show_nav: true

nav:
  - title: "Home"
    url: "/docs/"
  - title: "Introduction"
    url: "/docs/intro/"
  - title: "Get Started"
    url: "/docs/get-started/"
    children:
      - title: "Play with Template"
        url: "/docs/get-started/play-with-template"
  - title: "Migrate Applications to TEE"
    url: "/docs/migration/"
    children:
      - title: "Expose Service Port"
        url: "/docs/migration/expose-service-port"
      - title: "Generate RA Report"
        url: "/docs/migration/generate-ra-report"
      - title: "Access Database"
        url: "/docs/migration/access-database"
      - title: "Create Crypto Wallet"
        url: "/docs/migration/create-crypto-wallet"
  - title: "CVM Development"
    url: "/docs/deployment/"
    children:
      - title: "Deploy with Docker Compose"
        url: "/docs/deployment/deploy-with-docker-compose"
      - title: "Set Secure Environment Variables"
        url: "/docs/deployment/set-secure-environment-variables"
      - title: "Deploy with Private Docker Image"
        url: "/docs/deployment/deploy-with-private-docker-image"
      - title: "Access Your Applications"
        url: "/docs/deployment/access-your-applications"
      - title: "Debug Your Application"
        url: "/docs/deployment/debug-your-application"
      - title: "Deployment Cheat Sheet"
        url: "/docs/deployment/deployment-cheat-sheet"
  - title: "CVM Management"
    url: "/docs/management/"
    children:
      - title: "Check Logs"
        url: "/docs/management/check-logs"
      - title: "Set Private Log Viewer"
        url: "/docs/management/private-log-viewer"
      - title: "Monitor Your Application"
        url: "/docs/management/monitor-your-application"
      - title: "Upgrade Application"
        url: "/docs/management/upgrade-application"
      - title: "Resize Resource"
        url: "/docs/management/resize-resource"
  - title: "Resources"
    url: "/docs/resources/"
  - title: "Cloud APIs"
    url: "/docs/cloud-api/"
  - title: "Reference Architectures"
    url: "/docs/references/"
  - title: "Pricing"
    url: "/docs/pricing/"
  - title: "FAQs"
    url: "/docs/faqs/"
  - title: "Glossary"
    url: "/docs/glossary/"
