title: Phala Cloud Docs
description: Phala Cloud is a cloud service that allows you to deploy arbitrary dockerized applications into TEE.
baseurl: "/phala-cloud-community"
url: "https://phala-network.github.io"
markdown: kramdown
highlighter: rouge
permalink: pretty
destination: docs
include:
  - imgs

theme: just-the-docs
just_the_docs:
  nav_fold: true
  search_enabled: true
  search:
    heading_level: 2
  collections:
    docs:
      output: true
  nav_order: 1

# Force all pages to use default layout
defaults:
  - scope:
      path: "" # All files
    values:
      layout: default
      show_nav: true

nav:
  - title: "Introduction"
    url: "/docs/intro/"
  - title: "Get Started"
    url: "/docs/get-started/"
  - title: "Migrate Applications to TEE"
    url: "/docs/migration/"
  - title: "CVM Development"
    has_children: true  # Critical for nesting
    children:
      - title: "Deploy with Docker Compose"
        url: "/docs/deployment/deploy-with-docker-compose"
      - title: "Set Secure Environment Variables"
        url: "/docs/deployment/set-secure-environment-variables"
      - title: "Deploy with Private Docker Image"
        url: "/docs/deployment/deploy-with-private-docker-image"
      - title: "Access Your Applications"
        url: "/docs/deployment/access-your-applications"
      - title: "Debug Your Application"
        url: "/docs/deployment/debug-your-application"
      - title: "Deployment Cheat Sheet"
        url: "/docs/deployment/deployment-cheat-sheet"
  - title: "CVM Management"
    url: "/docs/management/"
  - title: "Resources"
    url: "/docs/resources/"
  - title: "Cloud APIs"
    url: "/docs/cloud-api/"
  - title: "Reference Architectures"
    url: "/docs/references/"
  - title: "Pricing"
    url: "/docs/pricing/"
  - title: "FAQs"
    url: "/docs/faqs/"
  - title: "Glossary"
    url: "/docs/glossary/"
