title: Phala Cloud Docs
description: Phala Cloud is a cloud service that allows you to deploy arbitrary dockerized applications into TEE.
baseurl: ""
url: "https://phala-network.github.io"
markdown: kramdown
highlighter: rouge
permalink: pretty
include:
  - imgs

theme: just-the-docs
just_the_docs:
  nav_fold: false
  nav_level: 2
  collapse_inactive_sections: false
  expand_all: true
  search_enabled: true
  search:
    heading_level: 2
  collections:
    docs:
      output: true
  nav_order: 1

# Force all pages to use default layout
defaults:
  - scope:
      path: "" # All files
    values:
      layout: default
      show_nav: true

nav:
  - title: "Home"
    url: "/docs/"
  - title: "Introduction"
    url: "/docs/intro/"
  - title: "Get Started"
    url: "/docs/get-started/"
    children:
      - title: "Play with Template"
        url: "/docs/get-started/play-with-template"
  - title: "Migrate Applications to TEE"
    url: "/docs/migration/"
    children:
      - title: "Expose Service Port"
        url: "/docs/migration/expose-service-port"
      - title: "Generate RA Report"
        url: "/docs/migration/generate-ra-report"
      - title: "Access Database"
        url: "/docs/migration/access-database"
      - title: "Create Crypto Wallet"
        url: "/docs/migration/create-crypto-wallet"
  - title: "CVM Development"
    url: "/docs/deployment/"
    children:
      - title: "Deploy with Docker Compose"
        url: "/docs/deployment/deploy-with-docker-compose"
      - title: "Set Secure Environment Variables"
        url: "/docs/deployment/set-secure-environment-variables"
      - title: "Deploy with Private Docker Image"
        url: "/docs/deployment/deploy-with-private-docker-image"
      - title: "Access Your Applications"
        url: "/docs/deployment/access-your-applications"
      - title: "Debug Your Application"
        url: "/docs/deployment/debug-your-application"
      - title: "Deployment Cheat Sheet"
        url: "/docs/deployment/deployment-cheat-sheet"
  - title: "CVM Management"
    url: "/docs/management/"
    children:
      - title: "Check Logs"
        url: "/docs/management/check-logs"
      - title: "Set Private Log Viewer"
        url: "/docs/management/private-log-viewer"
      - title: "Monitor Your Application"
        url: "/docs/management/monitor-your-application"
      - title: "Upgrade Application"
        url: "/docs/management/upgrade-application"
      - title: "Resize Resource"
        url: "/docs/management/resize-resource"
  - title: "Resources"
    url: "/docs/resources/"
  - title: "Cloud APIs"
    url: "/docs/cloud-api/"
  - title: "Reference Architectures"
    url: "/docs/references/"
  - title: "Pricing"
    url: "/docs/pricing/"
  - title: "FAQs"
    url: "/docs/faqs/"
  - title: "Glossary"
    url: "/docs/glossary/"
