name: Build and deploy Jekyll site
on:
  push:
    branches: [ main ]
permissions:
  contents: write  # Add this permissions block
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false  # Important for token auth

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Build with Jekyll
      uses: helaili/jekyll-action@2.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Explicit token declaration
        target_branch: gh-pages
        build_dir: .
